name: geofence_alarm
description: A location-based alarm application that triggers when user enters a geofence area.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  flutter_foreground_task: ^9.2.2
  flutter_local_notifications: ^21.0.0
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.1
  permission_handler: ^12.0.1
  flutter_ringtone_player: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
